import asyncio
URL='http://localhost:8765/'   # eerst: python -m http.server 8765 -d docs  (ophalen werkt niet via file://)
from playwright.async_api import async_playwright
async def main():
    async with async_playwright() as p:
        b=await p.chromium.launch()
        ctx=await b.new_context(viewport={'width':1280,'height':1100},locale='nl-NL',accept_downloads=True)
        pg=await ctx.new_page(); errs=[]
        pg.on('console',lambda m: errs.append(m.text) if m.type=='error' and 'ERR_TUNNEL' not in m.text else None)
        pg.on('pageerror',lambda e: errs.append('PAGEERR '+str(e)))
        await pg.goto(URL+'raadzoeker.html')
        await pg.wait_for_function("document.getElementById('loadtxt').textContent.includes('spreekbeurten ·')",timeout=120000)
        await pg.click('.tabs [data-view=z]'); await pg.wait_for_timeout(300)
        print('toez:',await pg.inner_text('.summary .n')); await pg.screenshot(path='v4_toez.png')
        await pg.fill('#q','parkeer | parkeren'); await pg.evaluate('update(false)'); await pg.wait_for_timeout(300)
        print(' parkeren:',await pg.inner_text('.summary .n'),'|',(await pg.inner_text('.card .snip'))[:200])
        await pg.click('.card [data-act=zread]'); await pg.wait_for_timeout(200); print(' reader focus',await pg.eval_on_selector_all('#rbody .focus','e=>e.length')); await pg.keyboard.press('Escape')
        async with pg.expect_download() as d: await pg.click('#csv')
        print(' csv',(await d.value).suggested_filename)
        await pg.click('.tabs [data-view=t]'); await pg.wait_for_timeout(300)
        await pg.fill('#q','betaald parkeren'); await pg.evaluate('update(false)'); await pg.wait_for_timeout(300)
        await pg.click('[data-mode=tl]'); await pg.wait_for_timeout(400)
        print('timeline: meetings',await pg.eval_on_selector_all('.tm','e=>e.length'),'items',await pg.eval_on_selector_all('.ti','e=>e.length'),'moties',await pg.eval_on_selector_all('.ti.mo2','e=>e.length'),'toez',await pg.eval_on_selector_all('.ti.tz2','e=>e.length'),await pg.evaluate('location.hash'))
        await pg.screenshot(path='v4_tl.png')
        await pg.click('.ti a'); await pg.wait_for_timeout(200); print(' reader:',(await pg.inner_text('#rtitle'))[:60]); await pg.keyboard.press('Escape')
        await pg.click('.tabs [data-view=i]'); await pg.wait_for_timeout(400)
        await pg.screenshot(path='v4_ins.png',full_page=True)
        await pg.click('.rise button'); await pg.wait_for_timeout(400); print('rise click ->',await pg.input_value('#q'),await pg.inner_text('.summary .n'))
        await pg.click('.tabs [data-view=i]'); await pg.wait_for_timeout(300)
        await pg.click('td[data-ins^="w:0:"]'); await pg.wait_for_timeout(400); print('coll click ->',await pg.input_value('#fs'),await pg.inner_text('.summary .n'))
        await pg.click('#home'); await pg.wait_for_timeout(200)
        print('errors',errs)
        await pg.set_viewport_size({'width':390,'height':800}); await pg.fill('#q','parkeernorm'); await pg.evaluate('update(false)'); await pg.click('[data-mode=tl]'); await pg.wait_for_timeout(300)
        print('hscroll',await pg.evaluate('document.documentElement.scrollWidth>innerWidth'))
        await b.close()
asyncio.run(main())
