import asyncio,time
URL='http://localhost:8765/'   # eerst: python -m http.server 8765 -d docs  (ophalen werkt niet via file://)
from playwright.async_api import async_playwright
async def main():
    async with async_playwright() as p:
        b=await p.chromium.launch()
        ctx=await b.new_context(viewport={'width':1280,'height':1000},locale='nl-NL',accept_downloads=True)
        await ctx.grant_permissions(['clipboard-read','clipboard-write'])
        pg=await ctx.new_page(); errs=[]
        pg.on('console',lambda m: errs.append(m.text) if m.type in('error',) else None)
        pg.on('pageerror',lambda e: errs.append('PAGEERR '+str(e)))
        t=time.time()
        await pg.goto(URL+'raadzoeker.html')
        await pg.wait_for_function("document.getElementById('loadtxt').textContent.includes('spreekbeurten ·')",timeout=120000)
        print('loaded',round(time.time()-t,1),await pg.inner_text('#loadtxt'))
        await pg.screenshot(path='v2_browse.png')
        async def n(): return await pg.inner_text('.summary .n')
        await pg.click('.chip:has-text("AI & algoritmen")'); await pg.wait_for_timeout(600)
        print('AI ->',await n(),'|',await pg.inner_text('.legend'))
        await pg.screenshot(path='v2_ai.png')
        await pg.click('.chip >> nth=0') if await pg.query_selector('.chip') else None
        await pg.fill('#q','parkeer | parkeren'); await pg.evaluate("update(false)"); await pg.wait_for_timeout(300)
        t=time.time(); await pg.evaluate("lastKey='';update(false)"); print('parkeren ->',await n(),round((time.time()-t)*1000),'ms')
        await pg.screenshot(path='v2_park.png',full_page=False)
        print('video links:',await pg.eval_on_selector_all('.card .src a','e=>e.slice(0,3).map(x=>x.textContent)'))
        async with pg.expect_download() as d: await pg.click('#csv')
        dl=await d.value; path=await dl.path(); s=open(path,encoding='utf-8-sig').read(); print('csv',dl.suggested_filename,len(s.splitlines()),'rows |',s.splitlines()[1][:230])
        await pg.click('.card [data-act=copy]'); print('CLIP:',(await pg.evaluate('navigator.clipboard.readText()'))[-420:])
        await pg.click('.tabs [data-view=m]'); await pg.wait_for_timeout(300)
        print('moties parkeren ->',await n()); await pg.screenshot(path='v2_moties.png')
        await pg.select_option('#fp','VVD'); await pg.select_option('#mres','1'); await pg.wait_for_timeout(400); print(' +VVD aangenomen ->',await n())
        await pg.click('.mo .ti'); await pg.wait_for_timeout(200); print(' reader:',await pg.inner_text('#rtitle'),'| focus',await pg.eval_on_selector_all('#rbody .focus','e=>e.length')); await pg.keyboard.press('Escape')
        async with pg.expect_download() as d: await pg.click('#csv')
        print(' csv',(await d.value).suggested_filename, await pg.evaluate('location.hash'))
        await pg.click('#reset'); await pg.wait_for_timeout(200); print('after reset motions ->',await n())
        await pg.click('.tabs [data-view=t]'); await pg.fill('#q','betaald parkeren'); await pg.fill('#fd1','2026-10-01'); await pg.evaluate("update(false)"); await pg.wait_for_timeout(300)
        print('1 okt ondertiteling ->',await n(),'|',await pg.inner_text('.card .who'))
        await pg.screenshot(path='v2_sub.png')
        await pg.click('.card [data-act=copy]'); print('CLIP4:',(await pg.evaluate('navigator.clipboard.readText()'))[-300:])
        print('heap',round(await pg.evaluate('performance.memory.usedJSHeapSize/1e6')),'errors',errs)
        await pg.set_viewport_size({'width':390,'height':800}); await pg.wait_for_timeout(200)
        print('hscroll',await pg.evaluate('document.documentElement.scrollWidth>innerWidth'))
        await b.close()
asyncio.run(main())
