import asyncio,time
URL='http://localhost:8765/'   # eerst: python -m http.server 8765 -d docs  (ophalen werkt niet via file://)
from playwright.async_api import async_playwright
async def main():
    async with async_playwright() as p:
        b=await p.chromium.launch()
        ctx=await b.new_context(viewport={'width':1280,'height':1100},locale='nl-NL',accept_downloads=True)
        pg=await ctx.new_page(); errs=[]
        pg.on('console',lambda m: errs.append(m.text) if m.type in('error',) else None)
        pg.on('pageerror',lambda e: errs.append('PAGEERR '+str(e)))
        await pg.goto(URL+'raadzoeker.html')
        await pg.wait_for_function("document.getElementById('loadtxt').textContent.includes('spreekbeurten ·')",timeout=120000)
        await pg.screenshot(path='v3_home.png')
        await pg.eval_on_selector('#over','e=>e.scrollIntoView()'); await pg.screenshot(path='v3_about.png')
        await pg.click('.chip:has-text("Parkeren")'); await pg.wait_for_timeout(500)
        print('parkeren:',await pg.inner_text('.summary .n'),'| zoom:',(await pg.inner_text('.zoom'))[:160].replace('\n',' / '))
        await pg.click('.zoom .chip:has-text("Vergunningen")'); await pg.wait_for_timeout(500)
        print(' sub:',await pg.inner_text('.summary .n'),'| on:',await pg.inner_text('.zoom .chip.on'))
        await pg.screenshot(path='v3_zoom.png')
        vb=await pg.query_selector('.card .vb'); print(' video btn:',await vb.inner_text() if vb else None)
        if vb:
            await vb.click(); await pg.wait_for_timeout(1500)
            print(' video modal on:',await pg.eval_on_selector('#video','e=>e.classList.contains("on")'),'|',await pg.inner_text('#vtitle'),'|',await pg.inner_text('#vjump'),'| box:',(await pg.inner_html('#vbox'))[:150])
            await pg.keyboard.press('Escape')
        await pg.click('.tabs [data-view=i]'); await pg.wait_for_timeout(400)
        await pg.screenshot(path='v3_ins.png',full_page=True)
        await pg.select_option('#insp','DENK'); await pg.wait_for_timeout(200)
        print(' profile DENK:',(await pg.inner_text('.chart.wide:last-of-type .hbars'))[:120].replace('\n',' '))
        await pg.click('.heat td[data-ins^="p:0:"]'); await pg.wait_for_timeout(500)
        print(' cell click ->',await pg.inner_text('.summary .n'),await pg.input_value('#fp'),await pg.evaluate('location.hash'))
        await pg.click('#home'); await pg.wait_for_timeout(300)
        print(' home:',bool(await pg.query_selector('.hero')),repr(await pg.input_value('#q')))
        await pg.click('#about'); await pg.wait_for_timeout(300)
        print('errors',errs)
        await pg.set_viewport_size({'width':390,'height':800}); await pg.wait_for_timeout(200)
        print('hscroll home',await pg.evaluate('document.documentElement.scrollWidth>innerWidth'))
        await pg.click('.tabs [data-view=i]'); await pg.wait_for_timeout(300)
        print('hscroll ins',await pg.evaluate('document.documentElement.scrollWidth>innerWidth'))
        await b.close()
asyncio.run(main())
